language: python

python: "2.7"

env:
  - TOXENV=py27
  - TOXENV=py33

# install dependencies
install:
  - pip install tox --use-mirrors
  - pip install .
  - pip install -e .[test]

# run tests
script: tox

