language: python
python:
  - "2.7"

# whitelist
branches:
  only:
    - distribution

# command to install dependencies
install:
  - python setup.py install
  - pip install coverage
# command to run tests
script:
  - "python setup.py test"
  - touch echo "import coverage; coverage.process_startup()" > subproc.pth
  - "python tests/run_coverage.py"